### ISSUE TITLE
question，owl site 流水线 yaml 生成 groovy 问题讨论

### ISSUE THREAD

**Issue by iTaa** [chinapnr/JR#80]
## owl site流水线 yaml 生成 groovy 问题如下：
1. 由于 yaml 结构通过缩进来表示，对空格缩进很敏感，textx 里使用 /\s*/ 正则来过滤空行或空格，导致无法解析标准 yaml 结构
2. owl site 流水线涉及到全局的 key , 和多层次嵌套功能，目前 JR 暂不支持

## 解决方案一：
- 针对问题1，可以采用较为复杂的正则表达式来解决缩进问题
- 针对问题2，需要 JR 为 owl site 流水线单独定制逻辑

## 解决方案二：
- 使用 python 版标准的 yaml 解析包去解析，解析到的 key 用 jinja 模板进行替换即可，不存在上述问题，但同样需要 JR 为 owl site 流水线单独定制逻辑。

## owl site 流水线部分 yaml 参考如下：
``` yaml
#应用名
application: tty
label: TTY DevOps Go!
language: java

pipline:
      # CI 流水线配置
      return1: 
        - name: return1
      	- module: module1
        - status: disable
        - agent: master
      A010: 
        - name: 代码检出
      	- module: Git-module-checkout
      	- status: enable
      	- agent: jenkinsJdk1.x_x
      	- gitUrl: git@xxx.xxx.xxx.xxx:xxx/xxx.git
```
